%YAML 1.2
---
batch_size: 500
clipnorm: 0
hidden_units: 40
learning_rate: 0.001
learning_rate_natGrad : 0
model_impl: complex_RNN
unitary_impl : full_natGradRMS
nb_epochs: 200
patience : 50
histfile : exp/history_mnist_fulluRNN
savefile : exp/model_mnist_fulluRNN.hdf5
flag_permute : False

