%YAML 1.2
---
batch_size: 128
clipnorm: 0
hidden_units: 128
learning_rate: 0.001
model_impl: complex_RNN
nb_epochs: 20
patience : 10
histfile : exp/history_mnist_restricteduRNN128_lr0-0001_patience5
savefile : exp/model_mnist_restricteduRNN128_lr0-0001_patience5.hdf5
flag_permute : False

