%YAML 1.2
---
batch_size: 128
clipnorm: 0
hidden_units: 256
learning_rate: 0.001
learning_rate_natGrad : 0.000001
model_impl: complex_RNN
unitary_impl : full_natGradRMS
nb_epochs: 20
patience : 10
histfile : exp/history_mnist_fulluRNN64_lr0-001_lrng0-000001_patience5_natGradRMS
savefile : exp/model_mnist_fulluRNN64_lr0-001_lrng0-000001_patience5_natGradRMS.hdf5
flag_permute : False

